### ISSUE TITLE
Organization of tabs at the bottom

### ISSUE THREAD

**Issue by georgeef** [moneymanagerex/mmex-ios#12]
The `Management` and `Settings` tabs at the bottom of the screen have a little confusing names.

`Settings` contains mostly information. Only `Default Payee/Status` are really settings. `Default Account` is very similar, but it appears in `Management`. Most important settings are in `Management`.

Proposal:
- Move `Per-Database Data` section from `Management` to `Settings`.
- Rename `Management` to `All`. Inside it, rename `Manage *` -> `All *`.

**Comment by guanlisheng** [comment]
The primary consideration is to have two levels of settings
1. Application level, e.g. version, default payee and txn status.  
2. Databases level, e.g. base currency, default account , switch data ( switch or creation)


But I like your idea to separate data and setting.

**Comment by georgeef** [comment]
The separation of settings in different levels can be implemented inside the Settings view, e.g., clear separation in two or more sections. Adding another settings tab could be an option, but better not to do it; it would take valuable space at the bottom of the screen for little benefit.
