### ISSUE TITLE
Appearance in iPad

### ISSUE THREAD

**Issue by georgeef** [moneymanagerex/mmex-ios#13]
I tested in the simulator with iPad Pro-11.

## Problems

- All tabs show content only at the sidebar, which by default is closed. The rest of the screen is unused for most of the views.

- Click on the main area closes the sidebar and leaves the screen totally empty.

## Proposal:

- In `Checking`, `Management`, `Settings`: keep the sidebar open if there is no content in the main area (the screen should never be totally empty).

- In `Insights`, `Add Transaction`: do not use the sidebar; show the view in the main area.

**Comment by guanlisheng** [comment]
#17 just lets it work (sort of) on iPad. and let's consider it along with #12

**Comment by georgeef** [comment]
good enough for now.
