### ISSUE TITLE
Bug in Enter split categories

### ISSUE THREAD

**Issue by georgeef** [moneymanagerex/mmex-ios#191]
## Version

- [X] 0.1.14 on iPhone SE
- [X] Xcode simulator

## Problem

- After `Enter` (in a new start) and after adding split categories, all splits after the first show the category of the first split.

**Comment by georgeef** [comment]
@guanlisheng
Not a nice fix, but it works ok for now.

**Comment by guanlisheng** [comment]
ok, I also noticed this flaw but didn't figure out why.

**Comment by guanlisheng** [comment]
if we limit the max split count per category, I would like to update `splits` to `Dict [DataId: ]` from `List[]`

thought?

**Comment by georgeef** [comment]
the problem was that the split ids in `ForEach(txn.splits)` are not unique. at this moment all new splits have the default id value (it was 0, I changed it to -1 in a previous PR), because they are not yet inserted into DB. Xcode gives a warning and lets the app run, however with wrong behavior.

i fixed it by using the category as an id, under the assumption that there is only one split per category. i now see that MMEX Desktop allows multiple splits per category, so this is not a good solution (better to be consistent with Desktop).

my proposal is to keep the splits as an ordered list (order may be important for the users), and to use the array index as id in `ForEach`. this will allow again multiple splits per category.

**Comment by guanlisheng** [comment]
Agreed.  `list.indices` would be ideal and now I got the root reason. thanks

**Comment by guanlisheng** [comment]
i will follow up this issue
